// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL4omLg4ZJyymH35fqtlbXm95ZtDr-OJk',
    appId: '1:174491303820:web:629923d3f7d223c2f1a0a9',
    messagingSenderId: '174491303820',
    projectId: 'ogasso-35be6',
    authDomain: 'ogasso-35be6.firebaseapp.com',
    storageBucket: 'ogasso-35be6.firebasestorage.app',
    measurementId: 'G-6W6SPNF6P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB52vmltfXzmI5pblR34v3FGHy3MNQd8H0',
    appId: '1:174491303820:android:635e7af3ea90ebe5f1a0a9',
    messagingSenderId: '174491303820',
    projectId: 'ogasso-35be6',
    storageBucket: 'ogasso-35be6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADpJbe9TcJUlA6cPGXojARP7laPvoDp8w',
    appId: '1:174491303820:ios:b17781d1659e35a9f1a0a9',
    messagingSenderId: '174491303820',
    projectId: 'ogasso-35be6',
    storageBucket: 'ogasso-35be6.firebasestorage.app',
    iosBundleId: 'com.example.ogassoEmploye',
  );
}
